[[redirects]]
  from = "/api/tenten/*"
  to = "/api/tenten/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "https://sp-taskify-api.vercel.app/1-10/:splat"  
  status = 200
  force = true
